package main

var MockListBuckets string = `<?xml version='1.0' encoding='utf-8'?>
<ListAllMyBucketsResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
    <Owner>
        <DisplayName>webfile</DisplayName>
        <ID>75aa57f09aa0c8caeab4f8c24e99d10f8e7faeebf76c078efc7c6caea54ba06a</ID>
    </Owner>
    <Buckets>
        <Bucket>
            <Name>test</Name>
            <CreationDate>2024-01-29T11:33:51.000Z</CreationDate>
        </Bucket>
    </Buckets>
</ListAllMyBucketsResult>`

var MockDescribeInstances string = `<?xml version="1.0" encoding="UTF-8"?>
<DescribeInstancesResponse xmlns="http://ec2.amazonaws.com/doc/2016-11-15/">
    <requestId>b13a10b7-e5ab-4f16-a9d3-e25a625a1e96</requestId>
    <reservationSet>
        <item>
            <reservationId>r-0cb0ac181fb7dc1d5</reservationId>
            <ownerId>433192899833</ownerId>
            <groupSet/>
            <instancesSet>
                <item>
                    <instanceId>i-0ac884d9302693b10</instanceId>
                    <imageId>ami-0d2eebbd05d415fd2</imageId>
                    <instanceState>
                        <code>80</code>
                        <name>stopped</name>
                    </instanceState>
                    <privateDnsName>ip-172-31-69-122.ec2.internal</privateDnsName>
                    <dnsName/>
                    <reason>User initiated (2023-08-22 17:42:32 GMT)</reason>
                    <keyName>firecracker</keyName>
                    <amiLaunchIndex>0</amiLaunchIndex>
                    <productCodes/>
                    <instanceType>c7g.metal</instanceType>
                    <launchTime>2023-06-20T09:17:44.000Z</launchTime>
                    <placement>
                        <availabilityZone>us-east-1f</availabilityZone>
                        <groupName/>
                        <tenancy>default</tenancy>
                    </placement>
                    <monitoring>
                        <state>disabled</state>
                    </monitoring>
                    <subnetId>subnet-065100e959c75cbf0</subnetId>
                    <vpcId>vpc-01d5115b3578c5e61</vpcId>
                    <privateIpAddress>172.31.69.122</privateIpAddress>
                    <sourceDestCheck>true</sourceDestCheck>
                    <groupSet>
                        <item>
                            <groupId>sg-0dbac8b8d4b65cd66</groupId>
                            <groupName>launch-wizard-11</groupName>
                        </item>
                    </groupSet>
                    <stateReason>
                        <code>Client.UserInitiatedShutdown</code>
                        <message>Client.UserInitiatedShutdown: User initiated shutdown</message>
                    </stateReason>
                    <architecture>arm64</architecture>
                    <rootDeviceType>ebs</rootDeviceType>
                    <rootDeviceName>/dev/xvda</rootDeviceName>
                    <blockDeviceMapping>
                        <item>
                            <deviceName>/dev/xvda</deviceName>
                            <ebs>
                                <volumeId>vol-087a9ed3abeffd64c</volumeId>
                                <status>attached</status>
                                <attachTime>2023-06-13T16:08:15.000Z</attachTime>
                                <deleteOnTermination>true</deleteOnTermination>
                            </ebs>
                        </item>
                        <item>
                            <deviceName>/dev/sdf</deviceName>
                            <ebs>
                                <volumeId>vol-0b0ee0316e1f03b08</volumeId>
                                <status>attached</status>
                                <attachTime>2023-06-15T14:33:49.000Z</attachTime>
                                <deleteOnTermination>false</deleteOnTermination>
                            </ebs>
                        </item>
                    </blockDeviceMapping>
                    <virtualizationType>hvm</virtualizationType>
                    <clientToken>29cd6c62-ff96-4e3b-9b5e-b6aa21799e41</clientToken>
                    <tagSet>
                        <item>
                            <key>Name</key>
                            <value>dev-firecracker-test</value>
                        </item>
                    </tagSet>
                    <hypervisor>xen</hypervisor>
                    <networkInterfaceSet>
                        <item>
                            <networkInterfaceId>eni-0a9767ef60f5f2058</networkInterfaceId>
                            <subnetId>subnet-065100e959c75cbf0</subnetId>
                            <vpcId>vpc-01d5115b3578c5e61</vpcId>
                            <description/>
                            <ownerId>433192899833</ownerId>
                            <status>in-use</status>
                            <macAddress>16:b1:90:44:3c:f7</macAddress>
                            <privateIpAddress>172.31.69.122</privateIpAddress>
                            <privateDnsName>ip-172-31-69-122.ec2.internal</privateDnsName>
                            <sourceDestCheck>true</sourceDestCheck>
                            <groupSet>
                                <item>
                                    <groupId>sg-0dbac8b8d4b65cd66</groupId>
                                    <groupName>launch-wizard-11</groupName>
                                </item>
                            </groupSet>
                            <attachment>
                                <attachmentId>eni-attach-0f26ff069bb2a3f62</attachmentId>
                                <deviceIndex>0</deviceIndex>
                                <status>attached</status>
                                <attachTime>2023-06-13T16:08:14.000Z</attachTime>
                                <deleteOnTermination>true</deleteOnTermination>
                                <networkCardIndex>0</networkCardIndex>
                            </attachment>
                            <privateIpAddressesSet>
                                <item>
                                    <privateIpAddress>172.31.69.122</privateIpAddress>
                                    <privateDnsName>ip-172-31-69-122.ec2.internal</privateDnsName>
                                    <primary>true</primary>
                                </item>
                            </privateIpAddressesSet>
                            <ipv6AddressesSet/>
                            <interfaceType>interface</interfaceType>
                        </item>
                    </networkInterfaceSet>
                    <iamInstanceProfile>
                        <arn>arn:aws:iam::433192899833:instance-profile/dev-firecracker-role</arn>
                        <id>AIPAWJXCPCT4YKVWH6IO7</id>
                    </iamInstanceProfile>
                    <ebsOptimized>true</ebsOptimized>
                    <enaSupport>true</enaSupport>
                    <cpuOptions>
                        <coreCount>64</coreCount>
                        <threadsPerCore>1</threadsPerCore>
                    </cpuOptions>
                    <capacityReservationSpecification>
                        <capacityReservationPreference>open</capacityReservationPreference>
                    </capacityReservationSpecification>
                    <hibernationOptions>
                        <configured>false</configured>
                    </hibernationOptions>
                    <enclaveOptions>
                        <enabled>false</enabled>
                    </enclaveOptions>
                    <metadataOptions>
                        <state>applied</state>
                        <httpTokens>required</httpTokens>
                        <httpPutResponseHopLimit>1</httpPutResponseHopLimit>
                        <httpEndpoint>enabled</httpEndpoint>
                        <httpProtocolIpv4>enabled</httpProtocolIpv4>
                        <httpProtocolIpv6>disabled</httpProtocolIpv6>
                        <instanceMetadataTags>disabled</instanceMetadataTags>
                    </metadataOptions>
                    <maintenanceOptions>
                        <autoRecovery>default</autoRecovery>
                    </maintenanceOptions>
                    <bootMode>uefi</bootMode>
                    <currentInstanceBootMode>uefi</currentInstanceBootMode>
                    <platformDetails>Linux/UNIX</platformDetails>
                    <usageOperation>RunInstances</usageOperation>
                    <usageOperationUpdateTime>2023-06-13T16:08:14.000Z</usageOperationUpdateTime>
                    <privateDnsNameOptions>
                        <hostnameType>ip-name</hostnameType>
                        <enableResourceNameDnsARecord>true</enableResourceNameDnsARecord>
                        <enableResourceNameDnsAAAARecord>false</enableResourceNameDnsAAAARecord>
                    </privateDnsNameOptions>
                </item>
            </instancesSet>
        </item>
    </reservationSet>
</DescribeInstancesResponse>
`
